use crate::definitions::SqlDataType;

#[non_exhaustive]
#[derive(Debug, PartialEq, Eq)]
pub struct StandardTypeInfo {
    pub type_name: &'static str,
    pub sql_type: SqlDataType,
    pub non_concise_type: SqlDataType,
    pub searchable: i32,
    pub is_case_sensitive: bool,
    pub fixed_prec_scale: bool,
    pub scale: Option<u16>,
    pub precision: Option<u16>,
    pub octet_length: Option<u16>,
    pub fixed_bytes_length: Option<u16>,
    pub literal_prefix: Option<&'static str>,
    pub literal_suffix: Option<&'static str>,
    pub sql_code: Option<i32>,
    pub is_auto_unique_value: Option<bool>,
    pub is_unsigned: Option<bool>,
    pub num_prec_radix: Option<u16>,
}

pub const SQL_SEARCHABLE: i32 = 3;
pub const SQL_PRED_BASIC: i32 = 2;
pub const SQL_PRED_NONE: i32 = 0;

impl StandardTypeInfo {
    pub const DOUBLE: StandardTypeInfo = StandardTypeInfo {
        type_name: "double",
        sql_type: SqlDataType::DOUBLE,
        non_concise_type: SqlDataType::DOUBLE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: true,
        scale: Some(15),
        precision: Some(15),
        octet_length: Some(8),
        fixed_bytes_length: Some(8),
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: Some(false),
        is_unsigned: Some(false),
        num_prec_radix: Some(10),
    };
    pub const STRING: StandardTypeInfo = StandardTypeInfo {
        type_name: "string",
        sql_type: SqlDataType::EXT_W_VARCHAR,
        non_concise_type: SqlDataType::VARCHAR,
        searchable: SQL_SEARCHABLE,
        is_case_sensitive: true,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: Some("'"),
        literal_suffix: Some("'"),
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const OBJECT: StandardTypeInfo = StandardTypeInfo {
        type_name: "object",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const ARRAY: StandardTypeInfo = StandardTypeInfo {
        type_name: "array",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const BINDATA: StandardTypeInfo = StandardTypeInfo {
        type_name: "binData",
        sql_type: SqlDataType::EXT_BINARY,
        non_concise_type: SqlDataType::EXT_BINARY,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const UNDEFINED: StandardTypeInfo = StandardTypeInfo {
        type_name: "undefined",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const OBJECTID: StandardTypeInfo = StandardTypeInfo {
        type_name: "objectId",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: Some(24),
        octet_length: Some(24),
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: Some(true),
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const BOOL: StandardTypeInfo = StandardTypeInfo {
        type_name: "bool",
        sql_type: SqlDataType::EXT_BIT,
        non_concise_type: SqlDataType::EXT_BIT,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: Some(1),
        octet_length: Some(1),
        fixed_bytes_length: Some(1),
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const DATE: StandardTypeInfo = StandardTypeInfo {
        type_name: "date",
        sql_type: SqlDataType::TIMESTAMP,
        non_concise_type: SqlDataType::DATETIME,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: true,
        scale: Some(3),
        precision: Some(23),
        octet_length: Some(16),
        fixed_bytes_length: Some(16),
        literal_prefix: Some("'"),
        literal_suffix: Some("'"),
        sql_code: Some(3),
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const NULL: StandardTypeInfo = StandardTypeInfo {
        type_name: "null",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const REGEX: StandardTypeInfo = StandardTypeInfo {
        type_name: "regex",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const DBPOINTER: StandardTypeInfo = StandardTypeInfo {
        type_name: "dbPointer",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const JAVASCRIPT: StandardTypeInfo = StandardTypeInfo {
        type_name: "javascript",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const SYMBOL: StandardTypeInfo = StandardTypeInfo {
        type_name: "symbol",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const JAVASCRIPTWITHSCOPE: StandardTypeInfo = StandardTypeInfo {
        type_name: "javascriptWithScope",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const INT: StandardTypeInfo = StandardTypeInfo {
        type_name: "int",
        sql_type: SqlDataType::INTEGER,
        non_concise_type: SqlDataType::INTEGER,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: true,
        scale: Some(0),
        precision: Some(10),
        octet_length: Some(4),
        fixed_bytes_length: Some(4),
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: Some(false),
        is_unsigned: Some(false),
        num_prec_radix: Some(10),
    };
    pub const TIMESTAMP: StandardTypeInfo = StandardTypeInfo {
        type_name: "timestamp",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const LONG: StandardTypeInfo = StandardTypeInfo {
        type_name: "long",
        sql_type: SqlDataType::EXT_BIG_INT,
        non_concise_type: SqlDataType::EXT_BIG_INT,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: true,
        scale: Some(0),
        precision: Some(19),
        octet_length: Some(8),
        fixed_bytes_length: Some(8),
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: Some(false),
        is_unsigned: Some(false),
        num_prec_radix: Some(10),
    };
    pub const DECIMAL: StandardTypeInfo = StandardTypeInfo {
        type_name: "decimal",
        // TODO SQL-1068: Change to SqlDataType::DECIMAL
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,          // TODO SQL-1068: Some(34),
        octet_length: None,       // TODO SQL-1068: Some(16),
        fixed_bytes_length: None, // TODO SQL-1068: Some(16),
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: Some(false),
        is_unsigned: Some(false),
        num_prec_radix: None,
    };
    pub const MINKEY: StandardTypeInfo = StandardTypeInfo {
        type_name: "minKey",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const MAXKEY: StandardTypeInfo = StandardTypeInfo {
        type_name: "maxKey",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_BASIC,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
    pub const BSON: StandardTypeInfo = StandardTypeInfo {
        type_name: "bson",
        sql_type: SqlDataType::UNKNOWN_TYPE,
        non_concise_type: SqlDataType::UNKNOWN_TYPE,
        searchable: SQL_PRED_NONE,
        is_case_sensitive: false,
        fixed_prec_scale: false,
        scale: None,
        precision: None,
        octet_length: None,
        fixed_bytes_length: None,
        literal_prefix: None,
        literal_suffix: None,
        sql_code: None,
        is_auto_unique_value: None,
        is_unsigned: None,
        num_prec_radix: None,
    };
}
