[package]
name = "macos_postinstall"
version = "0.0.0"
authors = ["Patrick Meredith <pmeredit@protonmail.com>"]
edition = "2021"

[dependencies]
rust-ini = "0.20.0"
itertools = { workspace = true }
lazy_static = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust-ini"]
