[package]
name = "widechar"
version = "0.1.0"
authors = ["Ryan Chipman <ryan@ryanchipman.com>",
    "Natacha Bagnard <natacha.bagnard@mongodb.com>",
    "Patrick Meredith <pmeredit@protonmail.com>"]
edition = "2021"

[dependencies]
widestring = "1.0.2"
